#!/usr/bin/env python

import re
		
def game_parse(data):
	for line in data:
		if re.search('[0-2]',line):
			msg = 'This is a monster.\n'
			#random.randint(1, 10)
		if re.search('[4-6]',line):
			msg = 'This is a wild animal.\n'
			#random.randint(1, 10)
		if re.search('[7-9]',line):
			msg = 'This is a zombie.\n'
			#random.randint(1, 10)
		if re.search('[3]',line):
			msg = 'Nothing is there.\n'
			#random.randint(1, 10)
		
	return (msg)
	
if __name__=='__main__':
	from sys import stdin, stdout, stderr
	
	name = raw_input('\n()xxxx{=====>\nPlease enter your name: ')
	stdout.write("Your name is " + name + " the strong\n")
	stdout.write("\nThe journey begins...")

	while True:
		stdout.write('\nHow many steps do you want to take into the forest? ')
		(event) = game_parse(stdin.readline())
		stdout.write(event)
